apiVersion: v1
kind: Service
metadata:
    name: "myrsgcluster-b49b"
    labels:
        app: "myrsgcluster-b49b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myrsgcluster-b49b"