on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myrsgacr.azurecr.io
        username: ${{ secrets.acr_myrsgacr_username }}
        password: ${{ secrets.acr_myrsgacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myrsgacr.azurecr.io/myrsgcluster:${{ github.sha }}
        docker push myrsgacr.azurecr.io/myrsgcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myrsgcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myrsgclustera39e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myrsgclustera39e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myrsgclustera39e
        container-registry-url: myrsgacr.azurecr.io
        container-registry-username: ${{ secrets.acr_myrsgacr_username }}
        container-registry-password: ${{ secrets.acr_myrsgacr_password }}
        secret-name: myrsgclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myrsgclustera39e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myrsgacr.azurecr.io/myrsgcluster:${{ github.sha }}
        imagepullsecrets: |
          myrsgclusterdockerauth